name: PlutonScheduler
version: '${project.version}'
main: net.plutondev.plutonschedulerv2.PlutonSchedulerV2
api-version: 1.16
authors: [ BrandonGouw ]
description: Ce plugin est un plugin qui gère les commandes qui pourraient être ajoutées en utilisant la configuration ou en jeu.

commands:
  plutonscheduler:
    aliases:
      - scheduler
